# Generated by Django 5.1.5 on 2025-02-13 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_productlike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductLike',
        ),
    ]
