# Generated by Django 5.1.5 on 2025-02-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_alter_customer_customer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimg',
            name='image',
            field=models.ImageField(default=None, upload_to='media/img/'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='productimg',
            name='is_provide',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Img',
        ),
    ]
