# Generated by Django 5.1.5 on 2025-02-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, default='media/products/default.webp', null=True, upload_to='media/products/'),
        ),
    ]
