# Generated by Django 5.1.5 on 2025-03-03 00:49

import ecommerce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_shoppingcart_quantity_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='invoice_prefix',
            field=models.CharField(default=ecommerce.models.generate_invoice_prefix, max_length=10, unique=True),
        ),
    ]
